version: '3.8'

services:
  hoyt-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    # Healthcheck to monitor bot status
    healthcheck:
      test: ["CMD", "node", "-e", "require('fs').accessSync('/usr/src/app/dist/main.js')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Limited resources to avoid excessive resource consumption
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M